# Generated by Django 3.2 on 2021-04-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='eid',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
